# Generated by Django 4.0.1 on 2022-01-16 03:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=144, null=True)),
                ('slug', models.SlugField(null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=144, null=True)),
                ('slug', models.SlugField(null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_embed_url', models.URLField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None)),
                ('published', models.BooleanField(db_index=True, default=False)),
                ('update_required', models.BooleanField(db_index=True, default=False)),
                ('upvotes', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('downvotes', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('categories', models.ManyToManyField(blank=True, to='help.Category')),
            ],
        ),
    ]
