# Generated by Django 4.0.1 on 2022-01-26 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_remove_article_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help.article')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help.category')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            # field=models.ManyToManyField(blank=True, to='help.Category'),
            field=models.ManyToManyField(blank=True, through='help.ArticleCategory', to='help.Category'),
        ),
    ]
