# Generated by Django 4.0.1 on 2022-02-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_article_categories_articlecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='faq',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='order',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, through='help.ArticleCategory', to='help.Category'),
        ),
    ]
