# Generated by Django 4.0.1 on 2022-02-01 21:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0004_article_faq_article_order_articlecategory_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='search_phrases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), blank=True, help_text='Specific phrases someone might type to find this article', null=True, size=None),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=144, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='articlecategory',
            constraint=models.UniqueConstraint(fields=('category', 'article'), name='unique_category_article'),
        ),
    ]
