# Generated by Django 4.0.1 on 2022-02-04 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0006_article_mobile_video_embed_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='articles',
        ),
        migrations.CreateModel(
            name='CourseArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1000)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help.article')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help.course')),
            ],
        ),
        migrations.AddConstraint(
            model_name='coursearticle',
            constraint=models.UniqueConstraint(fields=('course', 'article'), name='unique_course_article'),
        ),
    ]
