# Generated by Django 4.0.1 on 2022-02-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0009_alter_coursearticle_options_article_discussion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, to='help.Article'),
        ),
    ]
